// Decompiled with JetBrains decompiler
// Type: ExileCore.Shared.Enums.InventoryNameE
// Assembly: ExileCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 482AC8CF-0A43-4326-80AE-90909BA2E467
// Assembly location: C:\Users\Dev_H\OneDrive\Documentos\Cosas para jueguitos\PoEHelper-3.22.0.1\ExileCore.dll

namespace ExileCore.Shared.Enums
{
  public enum InventoryNameE
  {
    None,
    MainInventory1,
    BodyArmour1,
    Weapon1,
    Offhand1,
    Helm1,
    Amulet1,
    Ring1,
    Ring2,
    Gloves1,
    Boots1,
    Belt1,
    Flask1,
    Cursor1,
    Map1,
    Weapon2,
    Offhand2,
    StrMasterCrafting,
    StrDexMasterCrafting,
    DexMasterCrafting,
    DexIntMasterCrafting,
    IntMasterCrafting,
    StrIntMasterCrafting,
    PVPMasterCrafting,
    PassiveJewels1,
    AnimatedArmour1,
    GuildTag1,
    StashInventoryId,
    DivinationCardTrade,
    Darkshrine,
    TalismanTrade,
    Leaguestone1,
    BestiaryCrafting,
    IncursionSacrifice,
    BetrayalUnveiling,
    ItemSynthesisInput,
    ItemSynthesisOutput,
    BlightCraftingInput,
    BlightCraftingItem,
    MetamorphosisGenomeInput,
    AtlasUpgrades1,
    AtlasUpgradesStorage,
    ExpeditionMapMission,
    ExpeditionDeal1,
    HarvestCraftingItem,
    HeistContractMission,
    HeistNpcEquipment1,
    HeistNpcEquipment2,
    HeistNpcEquipment3,
    HeistNpcEquipment4,
    HeistNpcEquipment5,
    HeistNpcEquipment6,
    HeistNpcEquipment7,
    HeistNpcEquipment8,
    HeistNpcEquipment9,
    Trinket1,
    HeistBlueprintMission,
    HeistStorage1,
    RitualSavedRewards1,
    DONOTUSE1,
    DONOTUSE2,
    DONOTUSE3,
    DONOTUSE4,
    RESERVED1,
    RESERVED2,
    RESERVED3,
    RESERVED4,
    UltimatumCraftingItem,
    RESERVED5,
    RESERVED6,
    ExpeditionStorage1,
    HellscapeModificationInventory1,
    LabyrinthCraftingInput,
    SentinelDroneInventory1,
    SentinelStorage1,
  }
}
