// Decompiled with JetBrains decompiler
// Type: ExileCore.Shared.Enums.ItemStatEnum
// Assembly: ExileCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 482AC8CF-0A43-4326-80AE-90909BA2E467
// Assembly location: C:\Users\Dev_H\OneDrive\Documentos\Cosas para jueguitos\PoEHelper-3.22.0.1\ExileCore.dll

namespace ExileCore.Shared.Enums
{
  public enum ItemStatEnum
  {
    Armor,
    EnergyShield,
    Evasion,
    AverageElementalDamage,
    AveragePhysicalDamage,
    AttackPerSecond,
    DPS,
    PhysicalDPS,
    WeaponCritChance,
    Sockets,
    LinkedSockets,
    Strength,
    Dexterity,
    Intelligence,
    AddedHP,
    AddedMana,
    AddedES,
    AddedESPercent,
    LightningResistance,
    FireResistance,
    ColdResistance,
    ChaosResistance,
    ElementalResistance,
    TotalResistance,
    LifeLeech,
    ManaLeech,
    Rarity,
    Quantity,
    CritChance,
    CritMultiplier,
    MovementSpeed,
    WeaponElementalDamagePercent,
    AddedLightningDamage,
    AddedFireDamage,
    AddedColdDamage,
    AddedPhysicalDamage,
    SpellDamage,
    FireDamagePercent,
    LightningDamagePercent,
    ColdDamagePercent,
    SpellCriticalChance,
    CastSpeed,
    ProjectileSpeed,
    MinionSkillLevel,
    FireSkillLevel,
    ColdSkillLevel,
    LightningSkillLevel,
    LocalPhysicalDamage,
    LocalPhysicalDamagePercent,
    LocalCritChance,
    LocalAttackSpeed,
    LocalAddedFireDamage,
    LocalAddedColdDamage,
    LocalAddedLightningDamage,
    LocalES,
    LocalEV,
    LocalArmor,
    LocalESPercent,
    LocalEVPercent,
    LocalArmorPercent,
  }
}
